default_platform(:ios)


# 1-
  desc "Create app on Apple Developer and App Store Connect sites"
# 2
  lane :create_app do
# 3
​    produce
  end

desc "Create adhoc build"
  lane :build_adhoc do
  gym(scheme: 'TestPods-QA', export_method: 'ad-hoc', output_directory: "./fastlane/builds/qa")
  end

desc "Create ipa"
  lane :build do
    # 1
    increment_build_number
    # 2
    gym
  end

desc "Testflight upload"
   lane :testflight do
      build
      pilot
   end

desc "Take screenshots"
  lane :screenshot do
    snapshot
  end


desc "Upload to App Store"
  lane :upload do
    deliver
  end

desc “Create app, take screenshots, build and upload to App Store"
  lane :release_app do
    create_app
    build
    screenshot
    upload
  end
