default_platform(:ios)

platform :ios do
# 1
  desc "Create app on Apple Developer and App Store Connect sites"
# 2
  lane :create_app do
# 3
​    produce
  end
end 

desc "Create ipa"
  lane :build do
    # 1
    increment_build_number
    # 2
    gym
  end

desc "Testflight upload"
   lane :testflight do
   upload_to_testflight
end
desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

desc "Upload to App Store"
  lane :upload do
    deliver
  end

desc “Create app, take screenshots, build and upload to App Store"
  lane :do_everything do
    create_app
    screenshot
    build
    upload
  end